package main

// mapLogSIP retruns a map with SIP stats which can be
// json encoded and send send as gelf to graylog
func (i *IPFIX) mapLogSIP() *map[string]interface{} {
	mLogSIP := map[string]interface{}{
		"version":       "1.1",
		"host":          *name,
		"short_message": i.SIP.SipMsg.Msg,
		"level":         "5",
		"_id":           i.SIP.SipMsg.CallId,
		"_from":         i.SIP.SipMsg.From.URI.User,
		"_to":           i.SIP.SipMsg.To.URI.User,
		"_method":       i.SIP.SipMsg.StartLine.Method,
		"_statusCode":   i.SIP.SipMsg.StartLine.Resp,
		"_ua":           i.SIP.SipMsg.UserAgent,
		"_srcIP":        stringIPv4(i.SIP.SrcIP),
		"_dstIP":        stringIPv4(i.SIP.DstIP),
		"_srcPort":      i.SIP.SrcPort,
		"_dstPort":      i.SIP.DstPort,
		"_ipLen":        i.SIP.IPlen,
		"_udpLen":       i.SIP.UDPlen,
		"_intVlan":      i.SIP.IntVlan,
		"_vl":           i.SIP.VL,
		"_tos":          i.SIP.TOS,
		"_tlen":         i.SIP.TLen,
		"_tid":          i.SIP.TID,
		"_tflags":       i.SIP.TFlags,
		"_ttl":          i.SIP.TTL,
		"_tproto":       i.SIP.TProto,
	}
	return &mLogSIP
}

// mapLogQOS retruns a map with QOS stats which can be
// json encoded and send as gelf to graylog
func (i *IPFIX) mapLogQOS() *map[string]interface{} {
	mLogQOS := map[string]interface{}{
		"version":             "1.1",
		"host":                *name,
		"short_message":       "LogQOS",
		"level":               5,
		"_incRtpBytes":        i.QOS.IncRtpBytes,
		"_incRtpPackets":      i.QOS.IncRtpPackets,
		"_incRtpLostPackets":  i.QOS.IncRtpLostPackets,
		"_incRtpAvgJitter":    i.QOS.IncRtpAvgJitter,
		"_incRtpMaxJitter":    i.QOS.IncRtpMaxJitter,
		"_incRtcpBytes":       i.QOS.IncRtcpBytes,
		"_incRtcpPackets":     i.QOS.IncRtcpPackets,
		"_incRtcpLostPackets": i.QOS.IncRtcpLostPackets,
		"_incRtcpAvgJitter":   i.QOS.IncRtcpAvgJitter,
		"_incRtcpMaxJitter":   i.QOS.IncRtcpMaxJitter,
		"_incRtcpAvgLat":      i.QOS.IncRtcpAvgLat,
		"_incRtcpMaxLat":      i.QOS.IncRtcpMaxLat,
		"_incrVal":            float64(i.QOS.IncrVal) / 100,
		"_incMos":             float64(i.QOS.IncMos) / 100,
		"_outRtpBytes":        i.QOS.OutRtpBytes,
		"_outRtpPackets":      i.QOS.OutRtpPackets,
		"_outRtpLostPackets":  i.QOS.OutRtpLostPackets,
		"_outRtpAvgJitter":    i.QOS.OutRtpAvgJitter,
		"_outRtpMaxJitter":    i.QOS.OutRtpMaxJitter,
		"_outRtcpBytes":       i.QOS.OutRtcpBytes,
		"_outRtcpPackets":     i.QOS.OutRtcpPackets,
		"_outRtcpLostPackets": i.QOS.OutRtcpLostPackets,
		"_outRtcpAvgJitter":   i.QOS.OutRtcpAvgJitter,
		"_outRtcpMaxJitter":   i.QOS.OutRtcpMaxJitter,
		"_outRtcpAvgLat":      i.QOS.OutRtcpAvgLat,
		"_outRtcpMaxLat":      i.QOS.OutRtcpMaxLat,
		"_outrVal":            float64(i.QOS.OutrVal) / 100,
		"_outMos":             float64(i.QOS.OutMos) / 100,
		"_type":               i.QOS.Type,
		"_callerIncSrcIP":     stringIPv4(i.QOS.CallerIncSrcIP),
		"_callerIncDstIP":     stringIPv4(i.QOS.CallerIncDstIP),
		"_callerIncSrcPort":   i.QOS.CallerIncSrcPort,
		"_callerIncDstPort":   i.QOS.CallerIncDstPort,
		"_calleeIncSrcIP":     stringIPv4(i.QOS.CalleeIncSrcIP),
		"_calleeIncDstIP":     stringIPv4(i.QOS.CalleeIncDstIP),
		"_calleeIncSrcPort":   i.QOS.CalleeIncSrcPort,
		"_calleeIncDstPort":   i.QOS.CalleeIncDstPort,
		"_callerOutSrcIP":     stringIPv4(i.QOS.CallerOutSrcIP),
		"_callerOutDstIP":     stringIPv4(i.QOS.CallerOutDstIP),
		"_callerOutSrcPort":   i.QOS.CallerOutSrcPort,
		"_callerOutDstPort":   i.QOS.CallerOutDstPort,
		"_calleeOutSrcIP":     stringIPv4(i.QOS.CalleeOutSrcIP),
		"_calleeOutDstIP":     stringIPv4(i.QOS.CalleeOutDstIP),
		"_calleeOutSrcPort":   i.QOS.CalleeOutSrcPort,
		"_calleeOutDstPort":   i.QOS.CalleeOutDstPort,
		"_callerIntSlot":      i.QOS.CallerIntSlot,
		"_callerIntPort":      i.QOS.CallerIntPort,
		"_callerIntVlan":      i.QOS.CallerIntVlan,
		"_calleeIntSlot":      i.QOS.CalleeIntSlot,
		"_calleeIntPort":      i.QOS.CalleeIntPort,
		"_calleeIntVlan":      i.QOS.CalleeIntVlan,
		"_beginTimeSec":       i.QOS.BeginTimeSec,
		"_beginTimeMic":       i.QOS.BeginTimeMic,
		"_endTimeSec":         i.QOS.EndTimeSec,
		"_endinTimeMic":       i.QOS.EndinTimeMic,
		"_duration":           int(i.QOS.EndTimeSec - i.QOS.BeginTimeSec),
		"_seperator":          i.QOS.Seperator,
		"_incRealm":           string(i.QOS.IncRealm),
		"_outRealm":           string(i.QOS.OutRealm),
		"_idLen":              i.QOS.IncCallIDLen,
		"_id":                 string(i.QOS.IncCallID),
		"_outCallIDLen":       i.QOS.OutCallIDLen,
		"_outCallID":          string(i.QOS.OutCallID),
	}
	return &mLogQOS
}

func (i *IPFIX) mapMetricQOS() map[string]interface{} {
	mMetricQOS := map[string]interface{}{
		"inc.rtp.mos":          float64(i.QOS.IncMos) / 100,
		"out.rtp.mos":          float64(i.QOS.OutMos) / 100,
		"inc.rtp.rval":         float64(i.QOS.IncrVal) / 100,
		"out.rtp.rval":         float64(i.QOS.OutrVal) / 100,
		"inc.rtp.packets":      float64(i.QOS.IncRtpPackets),
		"out.rtp.packets":      float64(i.QOS.OutRtpPackets),
		"inc.rtcp.packets":     float64(i.QOS.IncRtcpPackets),
		"out.rtcp.packets":     float64(i.QOS.OutRtcpPackets),
		"inc.rtp.lostPackets":  float64(i.QOS.IncRtpLostPackets),
		"out.rtp.lostPackets":  float64(i.QOS.OutRtpLostPackets),
		"inc.rtcp.lostPackets": float64(i.QOS.IncRtcpLostPackets),
		"out.rtcp.lostPackets": float64(i.QOS.OutRtcpLostPackets),
		"inc.rtp.avgJitter":    float64(i.QOS.IncRtpAvgJitter),
		"out.rtp.avgJitter":    float64(i.QOS.OutRtpAvgJitter),
		"inc.rtp.maxJitter":    float64(i.QOS.IncRtpMaxJitter),
		"out.rtp.maxJitter":    float64(i.QOS.OutRtpMaxJitter),
		"inc.rtcp.avgJitter":   float64(i.QOS.IncRtcpAvgJitter),
		"out.rtcp.avgJitter":   float64(i.QOS.OutRtcpAvgJitter),
		"inc.rtcp.maxJitter":   float64(i.QOS.IncRtcpMaxJitter),
		"out.rtcp.maxJitter":   float64(i.QOS.OutRtcpMaxJitter),
		"inc.rtcp.avgLat":      float64(i.QOS.IncRtcpAvgLat),
		"out.rtcp.avgLat":      float64(i.QOS.OutRtcpAvgLat),
		"inc.rtcp.maxLat":      float64(i.QOS.IncRtcpMaxLat),
		"out.rtcp.maxLat":      float64(i.QOS.OutRtcpMaxLat),
	}
	return mMetricQOS
}

// mapAllQOS retruns a map with QOS33 stats which can be
// json encoded and send into homer, or graylog
func (i *IPFIX) mapAllQOS() *map[string]interface{} {
	mAllQOS := map[string]interface{}{
		"INC_ID":              string(i.QOS.IncCallID),
		"INC_RTP_BYTE":        i.QOS.IncRtpBytes,
		"INC_RTP_PK":          i.QOS.IncRtpPackets,
		"INC_RTP_PK_LOSS":     i.QOS.IncRtpLostPackets,
		"INC_RTP_AVG_JITTER":  i.QOS.IncRtpAvgJitter,
		"INC_RTP_MAX_JITTER":  i.QOS.IncRtpMaxJitter,
		"INC_RTCP_BYTE":       i.QOS.IncRtcpBytes,
		"INC_RTCP_PK":         i.QOS.IncRtcpPackets,
		"INC_RTCP_PK_LOSS":    i.QOS.IncRtcpLostPackets,
		"INC_RTCP_AVG_JITTER": i.QOS.IncRtcpAvgJitter,
		"INC_RTCP_MAX_JITTER": i.QOS.IncRtcpMaxJitter,
		"INC_RTCP_AVG_LAT":    i.QOS.IncRtcpAvgLat,
		"INC_RTCP_MAX_LAT":    i.QOS.IncRtcpMaxLat,
		"INC_MOS":             i.QOS.IncMos,
		"INC_RVAL":            i.QOS.IncrVal,
		"CALLER_VLAN":         i.QOS.CallerIntVlan,
		"CALLER_SRC_IP":       stringIPv4(i.QOS.CallerIncSrcIP),
		"CALLER_SRC_PORT":     i.QOS.CallerIncSrcPort,
		"CALLER_DST_IP":       stringIPv4(i.QOS.CallerOutDstIP),
		"CALLER_DST_PORT":     i.QOS.CallerOutDstPort,
		"INC_REALM":           string(i.QOS.IncRealm),

		"OUT_ID":              string(i.QOS.OutCallID),
		"OUT_RTP_BYTE":        i.QOS.OutRtpBytes,
		"OUT_RTP_PK":          i.QOS.OutRtpPackets,
		"OUT_RTP_PK_LOSS":     i.QOS.OutRtpLostPackets,
		"OUT_RTP_AVG_JITTER":  i.QOS.OutRtpAvgJitter,
		"OUT_RTP_MAX_JITTER":  i.QOS.OutRtpMaxJitter,
		"OUT_RTCP_BYTE":       i.QOS.OutRtcpBytes,
		"OUT_RTCP_PK":         i.QOS.OutRtcpPackets,
		"OUT_RTCP_PK_LOSS":    i.QOS.OutRtcpLostPackets,
		"OUT_RTCP_AVG_JITTER": i.QOS.OutRtcpAvgJitter,
		"OUT_RTCP_MAX_JITTER": i.QOS.OutRtcpMaxJitter,
		"OUT_RTCP_AVG_LAT":    i.QOS.OutRtcpAvgLat,
		"OUT_RTCP_MAX_LAT":    i.QOS.OutRtcpMaxLat,
		"OUT_MOS":             i.QOS.OutMos,
		"OUT_RVAL":            i.QOS.OutrVal,
		"CALLEE_VLAN":         i.QOS.CalleeIntVlan,
		"CALLEE_SRC_IP":       stringIPv4(i.QOS.CalleeOutSrcIP),
		"CALLEE_SRC_PORT":     i.QOS.CalleeOutSrcPort,
		"CALLEE_DST_IP":       stringIPv4(i.QOS.CalleeIncDstIP),
		"CALLEE_DST_PORT":     i.QOS.CalleeIncDstPort,
		"OUT_REALM":           string(i.QOS.OutRealm),
		"MEDIA_TYPE":          i.QOS.Type,
	}
	return &mAllQOS
}

// mapIncQOS retruns a map with incomming RTP QOS stats which can be
// json encoded and send into homer, or graylog
func (i *IPFIX) mapIncQOS() *map[string]interface{} {
	mIncQOS := map[string]interface{}{

		"CORRELATION_ID":  string(i.QOS.IncCallID),
		"RTP_SIP_CALL_ID": string(i.QOS.IncCallID),
		"REPORT_TS":       i.QOS.BeginTimeSec,
		"TL_BYTE":         i.QOS.IncRtpBytes,
		"SKEW":            0.000,
		"TOTAL_PK":        i.QOS.IncRtpPackets,
		"EXPECTED_PK":     (i.QOS.IncRtpPackets + i.QOS.IncRtpLostPackets),
		"PACKET_LOSS":     i.QOS.IncRtpLostPackets,
		"SEQ":             0,
		"JITTER":          i.QOS.IncRtpAvgJitter,
		"MAX_JITTER":      i.QOS.IncRtpMaxJitter,
		"MEAN_JITTER":     i.QOS.IncRtpAvgJitter,
		"DELTA":           i.QOS.IncRtcpAvgLat,
		"MAX_DELTA":       i.QOS.IncRtcpMaxLat,
		"MAX_SKEW":        0.000,
		"MIN_MOS":         i.QOS.IncMos,
		"MEAN_MOS":        i.QOS.IncMos,
		"MOS":             i.QOS.IncMos,
		"RFACTOR":         i.QOS.IncrVal,
		"MIN_RFACTOR":     i.QOS.IncrVal,
		"MEAN_RFACTOR":    i.QOS.IncrVal,
		"SRC_IP":          stringIPv4(i.QOS.CallerIncSrcIP),
		"SRC_PORT":        i.QOS.CallerIncSrcPort,
		"DST_IP":          stringIPv4(i.QOS.CallerIncDstIP),
		"DST_PORT":        i.QOS.CallerIncDstPort,
		"SRC_MAC":         "00-00-00-00-00-00",
		"DST_MAC":         "00-00-00-00-00-00",
		"OUT_ORDER":       0,
		"SSRC_CHG":        0,
		"CODEC_PT":        i.QOS.Type,
		"CLOCK":           8000,
		"CODEC_NAME":      i.QOS.Type,
		"DIR":             0,
		"REPORT_NAME":     string(i.QOS.IncRealm),
		"PARTY":           0,
		"TYPE":            "PERIODIC",
	}
	return &mIncQOS
}

// mapOutQOS retruns a map with outgoing RTP QOS stats which can be
// json encoded and send into homer, or graylog
func (i *IPFIX) mapOutQOS() *map[string]interface{} {
	mOutQOS := map[string]interface{}{

		"CORRELATION_ID":  string(i.QOS.OutCallID),
		"RTP_SIP_CALL_ID": string(i.QOS.OutCallID),
		"REPORT_TS":       i.QOS.BeginTimeSec,
		"TL_BYTE":         i.QOS.OutRtpBytes,
		"SKEW":            0.000,
		"TOTAL_PK":        i.QOS.OutRtpPackets,
		"EXPECTED_PK":     (i.QOS.OutRtpPackets + i.QOS.OutRtpLostPackets),
		"PACKET_LOSS":     i.QOS.OutRtpLostPackets,
		"SEQ":             0,
		"JITTER":          i.QOS.OutRtpAvgJitter,
		"MAX_JITTER":      i.QOS.OutRtpMaxJitter,
		"MEAN_JITTER":     i.QOS.OutRtpAvgJitter,
		"DELTA":           i.QOS.OutRtcpAvgLat,
		"MAX_DELTA":       i.QOS.OutRtcpMaxLat,
		"MAX_SKEW":        0.000,
		"MIN_MOS":         i.QOS.OutMos,
		"MEAN_MOS":        i.QOS.OutMos,
		"MOS":             i.QOS.OutMos,
		"RFACTOR":         i.QOS.OutrVal,
		"MIN_RFACTOR":     i.QOS.OutrVal,
		"MEAN_RFACTOR":    i.QOS.OutrVal,
		"SRC_IP":          stringIPv4(i.QOS.CalleeOutSrcIP),
		"SRC_PORT":        i.QOS.CalleeOutSrcPort,
		"DST_IP":          stringIPv4(i.QOS.CalleeOutDstIP),
		"DST_PORT":        i.QOS.CalleeOutDstPort,
		"SRC_MAC":         "00-00-00-00-00-00",
		"DST_MAC":         "00-00-00-00-00-00",
		"OUT_ORDER":       0,
		"SSRC_CHG":        0,
		"CODEC_PT":        i.QOS.Type,
		"CLOCK":           8000,
		"CODEC_NAME":      i.QOS.Type,
		"DIR":             0,
		"REPORT_NAME":     string(i.QOS.OutRealm),
		"PARTY":           1,
		"TYPE":            "PERIODIC",
	}
	return &mOutQOS
}

/*
// mapIncQOS retruns a map with incomming RTCP QOS stats which can be
// json encoded and send into homer, or graylog
func (i *IPFIX) mapIncQOS() *map[string]interface{} {
	mIncQOS := map[string]interface{}{

		"CORRELATION_ID":  string(i.QOS.IncCallID),
		"RTP_SIP_CALL_ID": string(i.QOS.IncCallID),
		"REPORT_TS":       i.QOS.BeginTimeSec,
		"TL_BYTE":         i.QOS.IncRtcpBytes,
		"SKEW":            0.000,
		"TOTAL_PK":        i.QOS.IncRtcpPackets,
		"EXPECTED_PK":     (i.QOS.IncRtcpPackets + i.QOS.IncRtcpLostPackets),
		"PACKET_LOSS":     i.QOS.IncRtcpLostPackets,
		"SEQ":             0,
		"JITTER":          i.QOS.IncRtcpAvgJitter,
		"MAX_JITTER":      i.QOS.IncRtcpMaxJitter,
		"MEAN_JITTER":     i.QOS.IncRtcpAvgJitter,
		"DELTA":           i.QOS.IncRtcpAvgLat,
		"MAX_DELTA":       i.QOS.IncRtcpMaxLat,
		"MAX_SKEW":        0.000,
		"MIN_MOS":         i.QOS.IncMos,
		"MEAN_MOS":        i.QOS.IncMos,
		"MOS":             i.QOS.IncMos,
		"RFACTOR":         i.QOS.IncrVal,
		"MIN_RFACTOR":     i.QOS.IncrVal,
		"MEAN_RFACTOR":    i.QOS.IncrVal,
		"SRC_IP":          stringIPv4(i.QOS.CallerIncSrcIP),
		"SRC_PORT":        i.QOS.CallerIncSrcPort,
		"DST_IP":          stringIPv4(i.QOS.CallerIncDstIP),
		"DST_PORT":        i.QOS.CallerIncDstPort,
		"SRC_MAC":         "00-00-00-00-00-00",
		"DST_MAC":         "00-00-00-00-00-00",
		"OUT_ORDER":       0,
		"SSRC_CHG":        0,
		"CODEC_PT":        i.QOS.Type,
		"CLOCK":           8000,
		"CODEC_NAME":      i.QOS.Type,
		"DIR":             0,
		"REPORT_NAME":     string(i.QOS.IncRealm),
		"PARTY":           0,
		"TYPE":            "PERIODIC",
	}
	return &mIncQOS
}

// mapOutQOS retruns a map with outgoing RTCP QOS stats which can be
// json encoded and send into homer, or graylog
func (i *IPFIX) mapOutQOS() *map[string]interface{} {
	mOutQOS := map[string]interface{}{
		"CORRELATION_ID":  string(i.QOS.OutCallID),
		"RTP_SIP_CALL_ID": string(i.QOS.OutCallID),
		"REPORT_TS":       i.QOS.BeginTimeSec,
		"TL_BYTE":         i.QOS.OutRtcpBytes,
		"SKEW":            0.000,
		"TOTAL_PK":        i.QOS.OutRtcpPackets,
		"EXPECTED_PK":     (i.QOS.OutRtcpPackets + i.QOS.OutRtcpLostPackets),
		"PACKET_LOSS":     i.QOS.OutRtcpLostPackets,
		"SEQ":             0,
		"JITTER":          i.QOS.OutRtcpAvgJitter,
		"MAX_JITTER":      i.QOS.OutRtcpMaxJitter,
		"MEAN_JITTER":     i.QOS.OutRtcpAvgJitter,
		"DELTA":           i.QOS.OutRtcpAvgLat,
		"MAX_DELTA":       i.QOS.OutRtcpMaxLat,
		"MAX_SKEW":        0.000,
		"MIN_MOS":         i.QOS.OutMos,
		"MEAN_MOS":        i.QOS.OutMos,
		"MOS":             i.QOS.OutMos,
		"RFACTOR":         i.QOS.OutrVal,
		"MIN_RFACTOR":     i.QOS.OutrVal,
		"MEAN_RFACTOR":    i.QOS.OutrVal,
		"SRC_IP":          stringIPv4(i.QOS.CalleeOutSrcIP),
		"SRC_PORT":        i.QOS.CalleeOutSrcPort,
		"DST_IP":          stringIPv4(i.QOS.CalleeOutDstIP),
		"DST_PORT":        i.QOS.CalleeOutDstPort,
		"SRC_MAC":         "00-00-00-00-00-00",
		"DST_MAC":         "00-00-00-00-00-00",
		"OUT_ORDER":       0,
		"SSRC_CHG":        0,
		"CODEC_PT":        i.QOS.Type,
		"CLOCK":           8000,
		"CODEC_NAME":      i.QOS.Type,
		"DIR":             0,
		"REPORT_NAME":     string(i.QOS.OutRealm),
		"PARTY":           1,
		"TYPE":            "PERIODIC",
	}
	return &mOutQOS
}
*/
